### ISSUE TITLE
Unnecessary if else statements

### ISSUE THREAD

**Issue by Shrey-Viradiya** [tirthasheshpatel/OOPS3#1]
In class DiningPhilosophers,  if(i==5) condition is unnecessary as i goes from 0 to 4 only.

        for(int i=0;i<5;i++) {
            if(i==5) {
                this.philosophers[i] = new Philosopher(this.forks[(i+1)%5], this.forks[i], "p"+i);
            }
            else this.philosophers[i] = new Philosopher(this.forks[i], this.forks[(i+1)%5], "p"+i);
            Thread t = new Thread(this.philosophers[i]);
            t.start();
        }

**Comment by tirthasheshpatel** [comment]
This issue has been fixed at master by this commit: [FIX: dining philosopher problem](https://github.com/tirthasheshpatel/OOPS3/tree/34f4e613d42b4c14d7f913e235b7428e3d8cc99e)
